const BALANCE = {
  xpToNext: (lvl) => Math.floor(44 * Math.pow(lvl, 1.42)),
  playerBaseStat: {
    atk: 8,
    def: 7,
    matk: 8,
    mdef: 7,
    spd: 6,
    hitEff: 7,
    hitRes: 6,
    critChance: 0,
    critDamage: 0,
    hp: 0,
    mp: 0,
  },
  playerStatPerLevel: {
    atk: 1.6,
    def: 1.3,
    matk: 1.6,
    mdef: 1.3,
    spd: 0.9,
    hitEff: 1.1,
    hitRes: 0.9,
    critChance: 0,
    critDamage: 0,
    hp: 0,
    mp: 0,
  },
  maxHp: (lvl, def) => Math.floor(78 + lvl * 14 + def * 2.2),
  maxMp: (lvl, mdef) => Math.floor(24 + lvl * 5 + mdef * 1.5),
  itemStatScalar: {
    atk: 1.32,
    def: 1.12,
    matk: 1.32,
    mdef: 1.12,
    spd: 0.68,
    hitEff: 0.86,
    hitRes: 0.86,
    elementDmg: 0.58,
    critChance: 0.4,
    critDamage: 1.08,
    hp: 4.0,
    mp: 1.8,
  },
  monsterLevelExponent: 1.14,
  monsterEarlyMercy: (dlvl) => 1 - 0.08 * U.clamp(1 - (dlvl - 1) / 9, 0, 1),
  roomCount: (lvl) => U.clamp(8 + Math.floor(lvl / 3), 8, 16),
  minCombatFraction: 0.32,
  maxNonCombatStreak: 2,
  difficulties: {
    normal: {
      label: 'Normal',
      monsterMult: 1.08,
      lootBonus: 0.0,
      boonRarityBonus: 0,
    },
    hard: {
      label: 'Hard',
      monsterMult: 1.32,
      lootBonus: 0.6,
      boonRarityBonus: 0.65,
    },
    nightmare: {
      label: 'Nightmare',
      monsterMult: 1.75,
      lootBonus: 1.3,
      boonRarityBonus: 1.4,
    },
  },
  initiativeJitter: 3,
  combatActionDelayMs: 430,
  elementalStrongMult: 1.25,
  elementalResistMult: 0.82,
  elementalPreysOn: {
    fire: 'ice',
    ice: 'lightning',
    lightning: 'poison',
    poison: 'holy',
    holy: 'dark',
    dark: 'fire',
  },
  strategyRamp: (dlvl) => U.clamp(((dlvl || 1) - 1) / 19, 0, 1),
  monsterChargeChance: (dlvl) => 0.06 + BALANCE.strategyRamp(dlvl) * 0.13,
  bossChargeCadence: (dlvl) => Math.round(6 - BALANCE.strategyRamp(dlvl) * 3),
  chargeDamageMult: 1.15,
  chargeDefPiercePct: 0.5,
  monsterUtilityChance: (dlvl) => 0.12 + BALANCE.strategyRamp(dlvl) * 0.22,
  monsterUtilityCooldown: 3,
  guardMitigation: 0.45,
  guardMitigationVsCharge: 0.65,
  guardManaRestorePct: 0.1,
};
