const BALANCE = {
  xpToNext: (lvl) => Math.floor(44 * Math.pow(lvl, 1.42)),
  playerBaseStat: {
    atk: 8,
    def: 7,
    matk: 8,
    mdef: 7,
    spd: 6,
    hitEff: 7,
    hitRes: 6,
    critChance: 0,
    critDamage: 0,
    hp: 0,
    mp: 0,
  },
  playerStatPerLevel: {
    atk: 1.6,
    def: 1.3,
    matk: 1.6,
    mdef: 1.3,
    spd: 0.9,
    hitEff: 1.1,
    hitRes: 0.9,
    critChance: 0,
    critDamage: 0,
    hp: 0,
    mp: 0,
  },
  maxHp: (lvl, def) => Math.floor(82 + lvl * 14 + def * 1.35),
  maxMp: (lvl, mdef) => Math.floor(26 + lvl * 5 + mdef),
  itemLevelExponent: 0.78,
  itemStatScalar: {
    atk: 1.32,
    def: 1.12,
    matk: 1.32,
    mdef: 1.12,
    spd: 0.68,
    hitEff: 0.86,
    hitRes: 0.86,
    elementDmg: 0.2,
    critChance: 0.13,
    critDamage: 0.35,
    hp: 4.0,
    mp: 1.8,
  },
  monsterLevelExponent: 1.28,
  monsterEarlyMercy: (dlvl) => 1 - 0.08 * U.clamp(1 - (dlvl - 1) / 9, 0, 1),
  monsterPackChance: (dlvl) => 0.2 + 0.24 * U.clamp((dlvl - 1) / 20, 0, 1),
  roomCount: (lvl) => U.clamp(8 + Math.floor(lvl / 3), 8, 16),
  minCombatFraction: 0.32,
  maxNonCombatStreak: 2,
  difficulties: {
    normal: {
      label: 'Normal',
      monsterMult: 1.12,
      endgamePressure: 0,
      lootBonus: 0.0,
      boonRarityBonus: 0,
    },
    hard: {
      label: 'Hard',
      monsterMult: 1.4,
      endgamePressure: 0.2,
      lootBonus: 0.6,
      boonRarityBonus: 0.65,
    },
    nightmare: {
      label: 'Nightmare',
      monsterMult: 1.9,
      endgamePressure: 0.45,
      lootBonus: 1.3,
      boonRarityBonus: 1.4,
    },
  },
  difficultyMultiplier: (difficulty, dlvl) =>
    difficulty.monsterMult *
    (1 + (difficulty.endgamePressure || 0) * U.clamp((Math.max(1, dlvl) - 10) / 40, 0, 1)),
  bossDurability: (dlvl) => 1 + 0.65 * U.clamp((Math.max(1, dlvl) - 15) / 35, 0, 1),
  materialBundleCost: (lvl) => Math.round(150 + Math.pow(Math.max(1, lvl), 1.35) * 13.5),
  initiativeJitter: 3,
  combatActionDelayMs: 430,
  damageVariance: [0.9, 1.1],
  damageMitigation: (defense, attackPower) =>
    U.clamp(defense / Math.max(1, defense + 14 + attackPower * 0.85), 0, 0.72),
  hitChance: (hitEff, hitRes) => U.clamp(85 + (hitEff - hitRes) * 0.28, 60, 97),
  baseCritChance: (hitEff) => 5 + Math.sqrt(Math.max(0, hitEff)) * 0.7,
  maxCritChance: 95,
  elementalStrongMult: 1.25,
  elementalResistMult: 0.82,
  elementalPreysOn: {
    fire: 'ice',
    ice: 'lightning',
    lightning: 'poison',
    poison: 'holy',
    holy: 'dark',
    dark: 'fire',
  },
  strategyRamp: (dlvl) => U.clamp(((dlvl || 1) - 1) / 19, 0, 1),
  monsterChargeChance: (dlvl) => 0.06 + BALANCE.strategyRamp(dlvl) * 0.13,
  bossChargeCadence: (dlvl) => Math.round(6 - BALANCE.strategyRamp(dlvl) * 3),
  chargeDamageMult: 1.15,
  chargeDefPiercePct: 0.5,
  monsterUtilityChance: (dlvl) => 0.12 + BALANCE.strategyRamp(dlvl) * 0.22,
  monsterUtilityCooldown: 3,
  guardMitigation: 0.45,
  guardMitigationVsCharge: 0.65,
  guardManaRestorePct: 0.1,
};
