const TIERS = [
  {
    id: 'common',
    name: 'Common',
    color: 'var(--t-common)',
    statCount: 1,
    uniqueTraits: 0,
    mythicTraits: 0,
    mult: 1.0,
    weight: 100,
    rollRange: [0.92, 1.08],
    traitValueMult: 0.72,
  },
  {
    id: 'uncommon',
    name: 'Uncommon',
    color: 'var(--t-uncommon)',
    statCount: 2,
    uniqueTraits: 0,
    mythicTraits: 0,
    mult: 1.5,
    weight: 55,
    rollRange: [0.98, 1.14],
    traitValueMult: 0.82,
  },
  {
    id: 'rare',
    name: 'Rare',
    color: 'var(--t-rare)',
    statCount: 3,
    uniqueTraits: 0,
    mythicTraits: 0,
    mult: 2.15,
    weight: 26,
    rollRange: [1.04, 1.2],
    traitValueMult: 0.92,
  },
  {
    id: 'ultra_rare',
    name: 'Ultra Rare',
    color: 'var(--t-ultra)',
    statCount: 4,
    uniqueTraits: 1,
    mythicTraits: 0,
    mult: 3.05,
    weight: 11,
    rollRange: [1.1, 1.27],
    traitValueMult: 1.0,
  },
  {
    id: 'unique',
    name: 'Unique',
    color: 'var(--t-unique)',
    statCount: 5,
    uniqueTraits: 2,
    mythicTraits: 0,
    mult: 4.25,
    weight: 5,
    rollRange: [1.16, 1.34],
    traitValueMult: 1.1,
  },
  {
    id: 'legendary',
    name: 'Legendary',
    color: 'var(--t-legendary)',
    statCount: 6,
    uniqueTraits: 2,
    mythicTraits: 0,
    mult: 5.8,
    weight: 1.6,
    rollRange: [1.23, 1.42],
    traitValueMult: 1.22,
  },
  {
    id: 'mythic_legendary',
    name: 'Mythic Legendary',
    color: 'var(--t-mythic1)',
    statCount: 7,
    uniqueTraits: 2,
    mythicTraits: 1,
    mult: 7.75,
    weight: 0.28,
    rollRange: [1.3, 1.5],
    traitValueMult: 1.38,
  },
];
const TIER_BY_ID = Object.fromEntries(TIERS.map((t) => [t.id, t]));
const SLOTS = [
  {
    id: 'weapon',
    label: 'Weapon',
    group: 'weapon',
    primary: ['atk', 'matk', 'critChance'],
  },
  { id: 'helmet', label: 'Helmet', group: 'armor', primary: ['def', 'mdef'] },
  {
    id: 'chest',
    label: 'Chest Armor',
    group: 'armor',
    primary: ['def', 'hitRes'],
  },
  { id: 'legs', label: 'Leg Armor', group: 'armor', primary: ['def', 'spd'] },
  { id: 'arms', label: 'Arm Guards', group: 'armor', primary: ['atk', 'def'] },
  {
    id: 'offhand',
    label: 'Off-Hand',
    group: 'weapon',
    primary: ['def', 'mdef'],
  },
  { id: 'boots', label: 'Boots', group: 'armor', primary: ['spd', 'hitEff'] },
  {
    id: 'accessory1',
    label: 'Accessory',
    group: 'accessory',
    primary: ['critChance', 'critDamage', 'hp', 'mp'],
  },
  {
    id: 'accessory2',
    label: 'Accessory',
    group: 'accessory',
    primary: ['critChance', 'critDamage', 'hp', 'mp'],
  },
  {
    id: 'artifact',
    label: 'Artifact',
    group: 'artifact',
    primary: ['critDamage', 'hp', 'mp'],
    rareSlot: true,
  },
];
