const DUNGEON_THEMES = [
  {
    id: 'crypt',
    name: 'The Sunken Crypt',
    icon: '⚰️',
    desc: 'Damp stone corridors thick with the smell of old bones.',
  },
  {
    id: 'warren',
    name: 'The Goblin Warren',
    icon: '🪓',
    desc: 'Crude tunnels, torch smoke, and the barking of raiders.',
  },
  {
    id: 'cavern',
    name: 'The Frozen Cavern',
    icon: '🧊',
    desc: 'Ice-slick passages that groan under their own weight.',
  },
  {
    id: 'foundry',
    name: 'The Ember Foundry',
    icon: '🔥',
    desc: 'Abandoned forges still glowing faintly in the dark.',
  },
  {
    id: 'sanctum',
    name: 'The Shadow Sanctum',
    icon: '🕯️',
    desc: 'A temple to something the wall-carvings refuse to name.',
  },
  {
    id: 'web',
    name: 'The Sunken Web',
    icon: '🕸️',
    desc: 'Silk curtains hang between pillars swallowed by roots.',
  },
  {
    id: 'foundry_ruins',
    name: 'The Rusted Foundry',
    icon: '⚙️',
    desc: 'Broken gears the size of wagon wheels, still faintly turning.',
  },
  {
    id: 'ossuary',
    name: 'The Bone Ossuary',
    icon: '🦴',
    desc: 'Walls built from the dead, stacked with unsettling care.',
  },
  {
    id: 'flooded_hall',
    name: 'The Flooded Hall',
    icon: '🌊',
    desc: 'Black water laps at broken columns, hiding what sank below.',
  },
  {
    id: 'thornwood',
    name: 'The Thornwood Vault',
    icon: '🌿',
    desc: 'Roots have grown through the mortar, patient and enormous.',
  },
  {
    id: 'starfall',
    name: 'The Starfall Scar',
    icon: '☄️',
    desc: 'A crater of black glass where something fell from the sky.',
  },
];
const NAME_PARTS = {
  prefixByTier: {
    common: [
      'Worn',
      'Plain',
      'Dull',
      'Simple',
      'Chipped',
      'Battered',
      'Crude',
      'Faded',
      'Basic',
      'Weathered',
      'Scuffed',
      'Nicked',
      'Rough',
      'Modest',
    ],
    uncommon: [
      'Sturdy',
      'Honed',
      'Reinforced',
      'Sound',
      'Weighted',
      'Balanced',
      'Polished',
      'Serviceable',
      'Tempered',
      'Solid',
      'Keen',
      'Steady',
      'Fitted',
      'Trusty',
    ],
    rare: [
      'Gleaming',
      'Runed',
      'Tempered',
      'Warded',
      'Etched',
      'Inscribed',
      'Hardened',
      'Enchanted',
      'Silvered',
      'Marked',
      'Sharpened',
      'Ornate',
      'Charmed',
      'Sanctified',
    ],
    ultra_rare: [
      'Radiant',
      'Blessed',
      'Storm-forged',
      'Deepcut',
      'Resonant',
      'Luminous',
      'Empowered',
      'Ancient',
      'Exalted',
      'Sovereign',
      'Prismatic',
      'Arcane',
      'Sunlit',
      'Ironbound',
    ],
    unique: [
      'Whispering',
      'Bloodbound',
      'Sundered',
      'Hollowed',
      'Grave-Kissed',
      'Nightforged',
      'Soulbound',
      'Wraithtouched',
      'Thornmarked',
      'Fatewoven',
      'Cinderborn',
      'Frostbitten',
      'Ashveiled',
      'Duskwrought',
    ],
    legendary: [
      'Godless',
      'Worldsplitter',
      'Ashborn',
      'Eternal',
      'Skybreaker',
      'Doomforged',
      'Kingsbane',
      'Starforged',
      'Wyrmslayer',
      'Oathbreaker',
      'Deathless',
      'Hellforged',
      'Titanborn',
      'Voidtouched',
    ],
    mythic_legendary: [
      'Reality-Torn',
      'Apocalyptic',
      'Star-Eaten',
      'Doomcaller',
      'Worldsend',
      'Genesis-Forged',
      'Heaven-Rending',
      'Timeless',
      'Cosmic',
      'Entropy-Bound',
      'Universe-Cracked',
      'Fatepiercing',
      'Existence-Ending',
      'Beyond-Mortal',
    ],
  },
  nounBySlot: {
    weapon: [
      'Blade',
      'Cleaver',
      'Fang',
      'Warhammer',
      'Scepter',
      'Dagger',
      'Maul',
      'Glaive',
      'Rapier',
      'Halberd',
      'Saber',
      'Cutlass',
    ],
    helmet: ['Circlet', 'Greathelm', 'Hood', 'Faceguard', 'Diadem', 'Casque', 'Barbute', 'Coif'],
    chest: ['Cuirass', 'Hauberk', 'Robe', 'Breastplate', 'Vestment', 'Plackart', 'Doublet'],
    legs: ['Greaves', 'Legwraps', 'Cuisses', 'Chausses', 'Poleyns'],
    arms: ['Vambraces', 'Gauntlets', 'Bracers', 'Cuffs', 'Armguards'],
    accessory1: ['Ring', 'Talisman', 'Charm', 'Sigil', 'Amulet', 'Pendant', 'Signet'],
    accessory2: ['Ring', 'Talisman', 'Charm', 'Sigil', 'Amulet', 'Pendant', 'Signet'],
    artifact: ['Relic', 'Idol', 'Shard', 'Core', 'Reliquary', 'Codex', 'Effigy'],
    offhand: ['Buckler', 'Aegis', 'Kite Shield', 'Wardplate', 'Bulwark', 'Pavise'],
    boots: ['Boots', 'Treads', 'Striders', 'Sabatons', 'Wraps', 'Greaves'],
  },
  suffixesByTier: {
    unique: [
      'of the Hollow King',
      'of Ember Wraiths',
      'of the Last Vigil',
      'of the Drowned Choir',
      'of Undying Frost',
      'of the Void Between',
      'of the Forgotten Star',
      'of Widows Grief',
      'of the Silent Chorus',
      'of the Ashen Throne',
      'of the Rusted Crown',
      'of the Nightloom',
      'of the Starfall Scar',
      'of the Bone Ossuary',
      'of the Plague Mother',
      'of the Drowned King',
      'of the Broken Vow',
      'of the Hungering Dark',
      'of Wolves and Ash',
      'of the Third Watch',
    ],
    legendary: [
      'of the Deathless Choir',
      'of the Sundered Sky',
      'of a Thousand Falls',
      'of the Endless Vigil',
      'of the World Below',
      'of the Last Ember',
      'of the Shattered Pantheon',
      'of the Forsaken Realm',
      'of the Eternal Storm',
      'of the Grave Unmarked',
      'of the Final Hour',
      'of the Withered Crown',
      'of the Bloodless Throne',
      'of the Wailing Deep',
      'of the Unmade',
      'of the Silent Apocalypse',
      "of the Kingslayer's Rest",
      'of the Ruined Pantheon',
      'of the Last Cathedral',
      'of Ten Thousand Graves',
    ],
    mythic_legendary: [
      'of the Unwritten End',
      'of the Devouring Star',
      'of the Last God',
      'of the Shattered Multiverse',
      'of the Timeless Abyss',
      'of Creation Undone',
      'of the Final Reckoning',
      'of the Infinite Hunger',
      'of the World That Was',
      'of the Nameless Void',
      'of the Collapsing Heavens',
      'of the Everlasting Ruin',
      'of the Absolute Dark',
      'of the Forgotten Genesis',
      'of the Endless Silence',
      'of the Last Light Extinguished',
      'of the Unmaking',
      'of the Severed Eternity',
      'of the Godless Dawn',
      'of All That Remains',
    ],
  },
  suffixes: [
    'of the Hollow King',
    'of Ember Wraiths',
    'of the Last Vigil',
    'of the Drowned Choir',
    'of Undying Frost',
    'of the Void Between',
    'of the Forgotten Star',
    'of Widows Grief',
    'of the Silent Chorus',
    'of the Ashen Throne',
    'of the Rusted Crown',
    'of the Nightloom',
    'of the Starfall Scar',
    'of the Bone Ossuary',
    'of the Plague Mother',
    'of the Drowned King',
  ],
};
